#!/usr/bin/env node
/**
 * Generate Hedera keypairs for a fresh deployment.
 *
 *   npx tsx scripts/hedera-keygen.ts
 *
 * Generates two ECDSA keypairs — a treasury and an agent — and prints the EVM
 * address for each. Sending HBAR to an EVM address on Hedera *auto-creates* the
 * account (lazy account creation), so these addresses are fundable before the
 * accounts exist.
 *
 * Private keys are written to .env.local (gitignored) and never printed, so
 * they do not end up in your shell history or scrollback.
 *
 * After funding, run `npx tsx scripts/hedera-resolve.ts` to look up the
 * assigned 0.0.x account ids.
 */

import { appendFileSync, existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { PrivateKey } from '@hiero-ledger/sdk'

const ENV_PATH = resolve(process.cwd(), '.env.local')

function generate(label: string) {
  const key = PrivateKey.generateECDSA()
  return {
    label,
    privateKey: key.toStringDer(),
    publicKey: key.publicKey.toStringDer(),
    evmAddress: `0x${key.publicKey.toEvmAddress()}`,
  }
}

function main() {
  const treasury = generate('treasury')
  const agent = generate('agent')

  const existing = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : ''

  for (const [name, k] of [
    ['HEDERA_OPERATOR_KEY', treasury],
    ['AGENT_PRIVATE_KEY', agent],
  ] as const) {
    if (new RegExp(`^${name}=.+`, 'm').test(existing)) {
      console.error(
        `\n  ${name} is already set in .env.local — refusing to overwrite.\n` +
          `  Remove it first if you really want a new key.\n`
      )
      process.exit(1)
    }
  }

  appendFileSync(
    ENV_PATH,
    [
      '',
      `# Generated by scripts/hedera-keygen.ts — ECDSA, Hedera testnet`,
      `HEDERA_KEY_TYPE=ECDSA`,
      `HEDERA_OPERATOR_KEY=${treasury.privateKey}`,
      `AGENT_PRIVATE_KEY=${agent.privateKey}`,
      `# Account ids are filled in by scripts/hedera-resolve.ts once funded.`,
      '',
    ].join('\n')
  )

  console.log(`\n\x1b[1mGenerated 2 keypairs → .env.local\x1b[0m (private keys not printed)\n`)

  for (const k of [treasury, agent]) {
    console.log(`  \x1b[1m${k.label}\x1b[0m`)
    console.log(`    EVM address : \x1b[36m${k.evmAddress}\x1b[0m`)
    console.log('')
  }

  console.log(`  \x1b[1mFund both addresses with testnet HBAR, then run:\x1b[0m`)
  console.log(`    npx tsx scripts/hedera-resolve.ts\n`)
  console.log(
    `  Sending HBAR to an EVM address auto-creates the Hedera account.\n` +
      `  Fund the treasury with more (it pays every worker); the agent needs\n` +
      `  little HBAR, since the x402 facilitator covers payment fees.\n`
  )
}

main()
